// camera default values
var CAMERA_DEFAULT_ALPHA_VALUE = -1.57;
var CAMERA_SPEED_ROTATION = 50;
var CAMERA_DEFAULT_BETA_VALUE = 1.4721;
var CAMERA_DEFAULT_DESKTOP_RADIUS_VALUE = 1.0000;
var CAMERA_DEFAULT_MOBILE_RADIUS_VALUE = 6.3035;

var CAMERA_NEAR_PLANE_VALUE = 0.047;
var CAMERA_FAR_PLANE_VALUE = 4702.8922;
var CAMERA_INERTIA = 0.65;
var FIELD_OF_VIEW = 0.8;
var CAMERA_SENSIBILITY = 0; // disable mouse right click panning
var CAMERA_PINCH_DELTA_PERCENTAGE = 0.01;
var CAMERA_WHEEL_DELTA_PERCENTAGE = 0.01;
var CAMERA_SPEED = 0.9406;
var CAMERA_LOWER_BETA_LIMIT = 1.4721;
var CAMERA_UPPER_BETA_LIMIT = 1.4721;
// for desktop mode
var CAMERA_DESKTOP_LOWER_RADIUS_LIMIT = 1.0000;
var CAMERA_DESKTOP_UPPER_RADIUS_LIMIT = 20.0000;
var CAMERA_DESKTOP_SCALLING_Z_VALUE = -2.8207;
var CAMERA_DEFAULT_TARGET_POSITION_X = -0.001;
var CAMERA_DEFAULT_TARGET_POSITION_Y = 0.49;
var CAMERA_DEFAULT_TARGET_POSITION_Z = -0.001;
// for mobile mode
var CAMERA_MOBILE_LOWER_RADIUS_LIMIT = 3.112;
var CAMERA_MOBILE_UPPER_RADIUS_LIMIT = 6.3035;
var CAMERA_MOBILE_SCALLING_Z_VALUE = -6.3035;
// transparency alpha strength, mode and level envionment intensity
var DEFAULT_ALPHA_VALUE = 1;
var ALPHA_STRENGTH = 0.1;
var ALPHABLEND = 2;
var DEFAULT_ENVIRONMENT_INTESITY = 1;
var DEFAULT_ENVIRONMENT_TEXTURE_PATH =
  "assets/TVS_RTR_310/environment/studio.env";
var SCENE_DEFAULT_ENVIRONMENT_IBL_INTENSITY = 1.0;
var MATERIAL_ENVIRONMENT_INTESITY = 0.2;
var SCENE_EXPOSURE_VALUE = 1.0;
// direction light default intensity
var DIRECTION_LIGHT_INTENSITY = 0.5;
// shadow mapSize value
var SHADOW_MAP_SIZE = 512;
// textures variables
var redBlackTexture;
var yellowTexture;
var blueTexture;

var TEXTURE_DEFAULT_VSCALE_VALUE = -1.0;
